### ISSUE TITLE
Missing task/build?

### ISSUE THREAD

**Issue by zkan** [waferbaby/usesthis#117]
I'm trying to set up the usesthis on my local machine from this instruction on Wiki: https://github.com/waferbaby/usesthis/wiki/So-You-Want-Your-Own-usesthis%3F

I found that there is no build script in the https://github.com/waferbaby/usesthis/tree/main/tasks. Could you suggest any command to run this website on a local machine, please? 

Thanks!

**Comment by waferbaby** [comment]
Oh wow, hello! I need to write up some actual docs!

**Comment by waferbaby** [comment]
@zkan Does the `tasks/publish` script work for you?

**Comment by zkan** [comment]
@waferbaby Yes, it works for me now. Thanks a lot!
