### ISSUE TITLE
Needs a logo.

### ISSUE THREAD

**Issue by saw** [waferbaby/usesthis#33]
I've noticed this project doesn't have a logo. Any ideas?

**Comment by waferbaby** [comment]
:trollface:, maybe?

**Comment by jcohen** [comment]
![uses THIS](http://media.giphy.com/media/EoNpDGC8JQyfC/giphy.gif)

**Comment by pdokas** [comment]
![](https://cloud.githubusercontent.com/assets/21479/5322958/ef21a13e-7c7f-11e4-8736-9f94f384d736.jpg)

**Comment by pdokas** [comment]
You monster.

**Comment by waferbaby** [comment]
FYI, added a logo in the end.
