### ISSUE TITLE
Integration with MailChimp

### ISSUE THREAD

**Issue by pablosproject** [waferbaby/usesthis#51]
Hi,

I'm an mobile developer, so I don't know if it's easy to do or not, but what about linking the publication of a new post with a MailChimp mailing list to notify all users when new interview are published?

Let me know if I can help setting it up and adding to the website.

**Comment by waferbaby** [comment]
Huh! Do you really think that's something people would want?

**Comment by pablosproject** [comment]
I'm pretty used on having newsletter coming into my inbox with fresh content. As I'm getting reed of all my RSS feed, I think this would be useful.

**Comment by waferbaby** [comment]
Hm, interesting, okay! I might ask about it on Twitter, see if people are keen. Thank you for the idea!

**Comment by pablosproject** [comment]
I'm also thinking in doing a simple iOS client (just as my weekend project for next weekend). The API are really cool. Do you think this can be a value for some users?

**Comment by waferbaby** [comment]
Wow, sure, that'd be neat! Love to see what you do :)

**Comment by pablosproject** [comment]
Nice!! Will try to put some time together for this.

**Comment by waferbaby** [comment]
Lovely!
