### ISSUE TITLE
Insert link in Markdown API

### ISSUE THREAD

**Issue by pablosproject** [waferbaby/usesthis#57]
Hi,

The API are currently getting to me markdown with not correct links, basically those just have the slug name. Could you make them output the real link of the software or hardware?

Here is an example:
`On the iPad I use [Procreate][procreate-ios] and [Adobe Sketch][photoshop-sketch-ios]. I like Procreate for how powerful the tool is, but nothing has been able to top Adobe Sketch's basic pencil tool`

**Comment by waferbaby** [comment]
That is definitely a bug! Will fix. :)

**Comment by waferbaby** [comment]
Okay, give that a shot?

**Comment by pablosproject** [comment]
Hey. Thanks for checking. Still not correct. Tried [this](https://usesthis.com/api/interviews/daniel.zarick), still have things like `I have an [iPhone 6s][iphone-6s], `

**Comment by waferbaby** [comment]
Oh, I mean I've added the actual links to the bottom of the content now, so it should render as Markdown correctly!

**Comment by pablosproject** [comment]
Ok, will give it a try.

**Comment by waferbaby** [comment]
How'd that go?

**Comment by pablosproject** [comment]
Looks good. Still had no time to go thorugh this, but will ping you if there are problems.

**Comment by waferbaby** [comment]
Rad! Re-open an issue if something goes wrong :)

**Comment by pablosproject** [comment]
Hi Daniel. I tried again and it looks good, except for some links that are blank, like [Atom][] in this call https://usesthis.com/api/interviews/daniel.zarick.
