### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by HammyHavoc** [waferbaby/usesthis#70]
Hey Daniel,

If I were to contribute some interviews via GitHub with myself, a colleague who is a composer, and another who is an editor and writer, would that be of interest? :- )

**Comment by waferbaby** [comment]
Hey! Appreciate the offer, but I have a very very (very) long and specific queue. However, if you wanna post your own on your site(s), and then send me the link, I'll happily share 'em on the @usesthis Twitter account :)
