### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by afro-nolan** [waferbaby/usesthis#74]
Spelling mistake in Parker Molleys post

**Comment by waferbaby** [comment]
Ooh, where abouts? Feel free to make a PR, if you like!

**Comment by waferbaby** [comment]
@afro-nolan Did you want to make a PR, or should I just find it and fix it? Happy either way!

**Comment by afro-nolan** [comment]
@waferbaby Yup, I just made the PR

**Comment by waferbaby** [comment]
Thank you, yay! Fixed!
