### ISSUE TITLE
Blank lines in tags are breaking UI

### ISSUE THREAD

**Issue by akflds** [waferbaby/usesthis#87]
Removing the web category in [this commit](https://github.com/waferbaby/usesthis/commit/980d6c8d392fd73db10beba3872c86fcab58d387
) has left some blank lines in the list of tags and seems to be breaking the UI a little, for example:

![image](https://user-images.githubusercontent.com/1186261/61768998-5aff8500-ae2c-11e9-8d06-308602fc30c7.png)

Removing these blank lines should resolve the issue, or maybe there's a way to have the style ignore them but that seems like more work.

**Comment by waferbaby** [comment]
Dang, I thought I'd caught all these - thank you so much! This should fix it: https://github.com/waferbaby/usesthis/commit/4b0405335fb7a7a68790082f2fe0202b95c082d5

**Comment by akflds** [comment]
Hey! That's tided up any trailing blank lines but didn't grab those with blank lines between tags (which is the case in the original screenshot) e.g.

```
---
title: Mike Hoye
summary: Fixer (Mozilla) 
categories:
- developer
- linux


- windows
---
```

Apologies for not being clearer in the original issue :(

**Comment by waferbaby** [comment]
Ooh, gotcha. Dang, how embarrassing. Fixed!
