### ISSUE TITLE
Accessibility-oriented guidance

### ISSUE THREAD

**Issue by sivark** [waferbaby/usesthis#97]
There's currently a thread on HN discussing tech/software tooling options for the visually impaired [fn1]. I think it would be fantastic if Usesthis could collect a section of interviews in this context, by inviting users with different kinds of challenges  (and feature this section prominently on the navbar). 

If you're looking for suggestions to kick things off, T.V. Raman might be interesting: https://en.wikipedia.org/wiki/T._V._Raman

[fn1]: https://news.ycombinator.com/item?id=22918980

**Comment by waferbaby** [comment]
Hell yes! Great idea. And I'll happily take any other suggestions!

**Comment by sivark** [comment]
Austin Hicks might be another interesting interviewee. See https://camlorn.net/files/resume.pdf & https://news.ycombinator.com/item?id=20883169

**Comment by waferbaby** [comment]
Amazing. Keep 'em coming, this is awesome.
